services:
  postgres:
    image: postgres:16-alpine
    container_name: lab-strava-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lab_strava_db
      POSTGRES_USER: lab_strava_user
      POSTGRES_PASSWORD: lab_strava_pass
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U lab_strava_user -d lab_strava_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
